[project]
name = "epub-to-audiobook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "ebooklib>=0.20",
    "lxml>=6.0.2",
    "numpy>=2.4.4",
    "soundfile>=0.13.1",
    "torch>=2.0",
    "vibevoice @ git+https://github.com/microsoft/VibeVoice.git",
]
